version: "2"
services:

  front:
    build: .
    container_name: load-balancer
    ports:
      - "3030:3030"
    networks:
      - lb_network

networks:
  lb_network:
    name: lb_network
    driver: bridge